GROUPS_WITH_LABELS = {
    "benign": ['Benign',
               'Likely_benign',
               'Benign/Likely_benign',
               'Benign|drug_response',
               'Likely_benign|other',
               'Likely_benign|drug_response|other',
               'Likely_benign|other, Likely_pathogenic|association'
               ], 
    "pathogenic": ['Pathogenic',
                   'Pathogenic/Likely_pathogenic',
                   'Pathogenic|other',
                   'Likely_pathogenic',
                   'Likely_pathogenic|association',
                   'Pathogenic/Likely_pathogenic|risk_factor',
                   'drug_response, Pathogenic/Likely_pathogenic'
                   ],
    "uncertain": ['Conflicting_classifications_of_pathogenicity',
                  'Conflicting_classifications_of_pathogenicity|drug_response|other',
                  'Conflicting_classifications_of_pathogenicity|association',
                  'Uncertain_significance'
                  ],
    "other": ['', 'not_provided']
    }

INFO_KEYS = ["CSQ", "RankResult", "RankScore", "CLNSIG", "AF", "DP", "GNOMAD_AF"]
CSQ_KEYS = ["Consequence", "SIFT", "PolyPhen", "gnomAD_AF", "COSMIC", "CLIN_SIG"]

CONSEQUENCE_ORDER = [
    "transcript_ablation",
    "splice_acceptor_variant", 
    "splice_donor_variant", 
    "stop_gained",         
    "frameshift_variant",
    "stop_lost",
    "start_lost",
    "transcript_amplification",
    "feature_elongation",
    "feature_elongation",
    "inframe_insertion",
    "inframe_deletion",
    "missense_variant",
    "protein_altering_variant",
    "splice_donor_5th_base_variant",
    "splice_region_variant",
    "splice_donor_region_variant",
    "splice_polypyrimidine_tract_variant",
    "incomplete_terminal_codon_variant",
    "start_retained_variant",
    "stop_retained_variant",
    "synonymous_variant",
    "coding_sequence_variant",
    "mature_miRNA_variant",
    "5_prime_UTR_variant",
    "3_prime_UTR_variant",
    "non_coding_transcript_exon_variant",
    "intron_variant",
    "NMD_transcript_variant",
    "non_coding_transcript_variant",
    "coding_transcript_variant",
    "upstream_gene_variant",
    "downstream_gene_variant",
    "TFBS_ablation",
    "TFBS_amplification",
    "TF_binding_site_variant",
    "regulatory_region_ablation",
    "regulatory_region_amplification",
    "regulatory_region_variant",
    "intergenic_variant",
    "sequence_variant",
    "not_reported"
]